type TTopics =
  | 'Thema des Monats'
  | 'Ukraine'
  | 'Klima'
  | 'Klimawandel'
  | 'News'
  | 'Berlin'
  | 'BERLIN'
  | 'Politik'
  | 'Wirtschaft'
  | 'Kultur'
  | 'Konzerttickets'
  | 'Panorama'
  | '1. FC Union'
  | 'Union'
  | 'Corona-Debatte'
  | 'Deutschland'
  | 'Debatte'
  | 'Ausland'
  | 'Food'
  | 'Verkehr'
  | 'Open Source'
  | 'Stil'
  | 'Ratgeber'
  | 'Abgeordnetenhaus'
  | 'Bildung'
  | 'Gesundheit'
  | 'Wohnen'
  | 'Sport'
  | 'Open Mind'
  | 'Open World'
  | 'Technologie'
  | 'B - History'
  | 'Abstandsregel'
  | 'Abgeordnetenhauswahl'
  | 'Abba'
  | 'Abitur'
  | 'Adana'
  | 'Polizeibericht Berlin'
  | 'Hamburg'
  | 'Anklam'
  | 'B+ plus'
  | 'Gesellschaft'
  | 'Wetter'
  | 'Alabama'
  | 'Aarhus'
  | 'Australien'
  | 'Hertha BSC';
