name: DEV Engage Smoke
on:
  workflow_dispatch:
jobs:
  smoke:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      USER_PASS: ${{ secrets.PASS }}
      COOKIE: ${{ secrets.COOKIE }}
      RP_TOKEN: ${{ secrets.RP_TOKEN }}
      ENV: dev
      TYPE: smoke
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: npm ci
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npm run test:smoke
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: reports/
          retention-days: 7
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          detailed_summary: true
          include_passed: true
          report_paths: '**/reports/report.xml'
          check_name: 'Engage App'
